[package]
name = "filesystem"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
crossterm = "0.29.0"
globset = "0.4.18"
libc = "0.2"
rayon = "1.11.0"
regex = "1.12.2"
time = { version = "0.3.44", features = ["macros", "formatting"] }
walkdir = "2.5.0"

[[bin]]
name = "cat"
path = "bin/cat.rs"

[[bin]]
name = "chmod"
path = "bin/chmod.rs"

[[bin]]
name = "chown"
path = "bin/chown.rs"

[[bin]]
name = "cp"
path = "bin/cp.rs"

[[bin]]
name = "cut"
path = "bin/cut.rs"

[[bin]]
name = "df"
path = "bin/df.rs"

[[bin]]
name = "find"
path = "bin/find.rs"

[[bin]]
name = "grep"
path = "bin/grep.rs"

[[bin]]
name = "head"
path = "bin/head.rs"

[[bin]]
name = "less"
path = "bin/less.rs"

[[bin]]
name = "ln"
path = "bin/ln.rs"

[[bin]]
name = "ls"
path = "bin/ls.rs"

[[bin]]
name = "mkdir"
path = "bin/mkdir.rs"

[[bin]]
name = "mv"
path = "bin/mv.rs"

[[bin]]
name = "rm"
path = "bin/rm.rs"

[[bin]]
name = "rmdir"
path = "bin/rmdir.rs"

[[bin]]
name = "sed"
path = "bin/sed.rs"

[[bin]]
name = "sort"
path = "bin/sort.rs"

[[bin]]
name = "tail"
path = "bin/tail.rs"

[[bin]]
name = "tar"
path = "bin/tar.rs"

[[bin]]
name = "touch"
path = "bin/touch.rs"

[[bin]]
name = "uniq"
path = "bin/uniq.rs"

[[bin]]
name = "wc"
path = "bin/wc.rs"